goods/urls.py
from django.urls import path
from goods import views

app_name = 'goods'

urlpatterns = [
    path('', views.catalog, name='index'),
    path('search/', views.catalog, name='search'),
    path('product/<slug:product_slug>/', views.product, name='product'),
    path('category/<slug:category_slug>/', views.catalog, name='category'),
]

kku/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('profile/', include('users.urls', namespace='users_profile')),
    path('', include('myapp.urls', namespace='myapp')),
    path('catalog/', include('goods.urls', namespace='catalog')),
    path('users/', include('users.urls', namespace='users')),
]


if settings.DEBUG:
    urlpatterns += [
        path('debug/', include('debug_toolbar.urls')),
    ]
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myapp/urls.py
from django.urls import path
from myapp import views  # Импортируем представления из приложения myapp

app_name = 'myapp'  # Устанавливаем пространство имен для маршрутов

urlpatterns = [
    path('', views.index, name='index'),  # Главная страница
    path('about/', views.about, name='about'),  # Страница 'О нас'
    path('cart/', views.cart_detail, name='cart_detail'),  # Страница корзины
    path('cart/add/<int:product_id>/', views.cart_add, name='cart_add'),  # Добавить товар в корзину
    path('cart/remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
]

goods/models.py
from django.db import models

class Categories(models.Model):
    name = models.CharField(max_length=150, unique=True, verbose_name="Название")
    slug = models.SlugField(max_length=200, unique=True, blank=True, null=True, verbose_name='URL')

    class Meta:
        db_table = 'goods_category'  # Измените имя таблицы
        verbose_name = 'Категорию'
        verbose_name_plural = 'Категории'

    def __str__(self) -> str:
        return self.name

class Products(models.Model):
    name = models.CharField(max_length=150, unique=True, verbose_name="Название")
    slug = models.SlugField(max_length=200, unique=True, blank=True, null=True, verbose_name='URL')
    description = models.TextField(blank=True, null=True, verbose_name='Описание')
    image = models.ImageField(upload_to='goods_images', blank=True, null=True, verbose_name="Изображение")
    price = models.DecimalField(default=0.00, max_digits=7, decimal_places=2, verbose_name='Цена')
    discount = models.DecimalField(default=0.00, max_digits=4, decimal_places=2, verbose_name='Скидка в %')
    quantity = models.PositiveIntegerField(default=0, verbose_name='Количество')
    category = models.ForeignKey(Categories, on_delete=models.CASCADE, verbose_name="Категория")

    class Meta:
        db_table = 'goods_product'  # Измените имя таблицы
        verbose_name = 'Товар'
        verbose_name_plural = 'Товары'

    def __str__(self) -> str:
        return self.name

goods/views.py
from django.shortcuts import render, redirect, get_object_or_404
from goods.models import Products, Categories
from goods.utils import q_search  # Убедитесь, что эта функция импортируется правильно
from django.core.paginator import Paginator

def catalog(request, category_slug=None):
    page = request.GET.get('page', 1)
    on_sale = request.GET.get('on_sale', None)
    order_by = request.GET.get('order_by', None)
    query = request.GET.get('q', None)

    goods = Products.objects.all()

    # Фильтрация по категории
    if category_slug and category_slug != "all":
        goods = goods.filter(category__slug=category_slug)

    # Поиск по запросу
    if query:
        goods = q_search(query)  # Убедитесь, что q_search работает правильно

    # Фильтрация по скидке
    if on_sale:
        goods = goods.filter(discount__gt=0)

    # Сортировка
    if order_by and order_by != "default":
        goods = goods.order_by(order_by)

    # Пагинация
    paginator = Paginator(goods, 3)  # 3 товара на страницу
    current_page = paginator.get_page(page)

    # Получение всех категорий
    categories = Categories.objects.all()

    context = {
        "title": "Каталог",
        "goods": current_page,
        "slug_url": category_slug,
        "categories": categories,
    }

    return render(request, 'goods/catalog.html', context)

def product(request, product_slug):
    product = get_object_or_404(Products, slug=product_slug)
    context = {
        "product": product,
    }
    return render(request, 'goods/product.html', context)

goods/templates/goods/catalog.html
{% extends "base.html" %}
{% load static %}
{% load goods_tags %}

{% block content %}
<div class="row">
    <!-- Форма фильтров -->
    <div class="dropdown mb-2">
        <button class="btn btn-secondary dropdown-toggle btn-dark" type="button" data-bs-toggle="dropdown" aria-expanded="false">
            Фильтры
        </button>
        <form action="{% if request.GET.q %}{% url 'catalog:search' %}{% else %}{% url 'catalog:index' %}{% endif %}" method="get" class="dropdown-menu bg-dark" data-bs-theme="dark">
            <div class="form-check text-white mx-3">
                <input class="form-check-input" type="checkbox" name="on_sale" id="flexCheckDefault" value="on" {% if request.GET.on_sale %}checked{% endif %}>
                {% if request.GET.q %}
                    <input type="hidden" name="q" value="{{ request.GET.q }}">
                {% endif %}
                <label class="form-check-label" for="flexCheckDefault">Товары по акции</label>
            </div>
            <button type="submit" class="btn btn-outline-light mx-3">Применить фильтр</button>
        </form>
    </div>

    <div class="row">
        {% if goods %}
            {% for product in goods %}
            <!-- Карта товара -->
            <div class="col-lg-4 col-md-6 p-4">
                <div class="card border-primary rounded custom-shadow">
                    {% if product.image %}
                        <img src="{{ product.image.url }}" class="card-img-top" alt="{{ product.name }}">
                    {% else %}
                        <img src="{% static 'deps/images/Not found image.png' %}" class="card-img-top" alt="Изображение не найдено">
                    {% endif %}
                    <div class="card-body">
                        <a href="{% url 'goods:product' product.slug %}">
                            <p class="card-title">{{ product.name }}</p>
                        </a>
                        <p class="card-text">{{ product.description|truncatechars:100 }}</p>
                        <p class="product_id">id: {{ product.display_id }}</p>
                        <div class="d-flex justify-content-between">
                            {% if product.discount %}
                                <p><s>{{ product.price }}</s> $</p>
                                <p><strong>{{ product.sell_price }}</strong> $</p>
                                <span class="badge bg-warning text-dark">Скидка {{ product.discount }} %</span>
                            {% else %}
                                <p><strong>{{ product.price }} $</strong></p>
                            {% endif %}
                            <form action="{% url 'myapp:cart_add' product.id %}" method="post">
                                {% csrf_token %}
                                <button type="submit" class="btn add-to-cart">
                                    <img class="mx-1" src="{% static 'deps/icons/cart-plus.svg' %}" alt="Добавить в корзину" width="32" height="32">
                                </button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
        {% else %}
            <p class="text-white">Товары не найдены.</p>
        {% endif %}
    </div>

    <!-- Пагинация -->
    <nav aria-label="Page navigation example">
        <ul class="pagination justify-content-center my-4">
            <div class="custom-shadow d-flex">
                <li class="page-item {% if not goods.has_previous %}disabled{% endif %}">
                    <a class="page-link" href="{% if goods.has_previous %}?{% change_params page=goods.previous_page_number %}{% else %}#{% endif %}">Назад</a>
                </li>

                {% for page in goods.paginator.page_range %}
                    {% if page >= goods.number|add:-2 and page <= goods.number|add:2 %}
                        <li class="page-item {% if goods.number == page %}active{% endif %}">
                            <a class="page-link" href="?{% change_params page=page %}">{{ page }}</a>
                        </li>
                    {% endif %}
                {% endfor %}

                <li class="page-item {% if not goods.has_next %}disabled{% endif %}">
                    <a class="page-link" href="{% if goods.has_next %}?{% change_params page=goods.next_page_number %}{% else %}#{% endif %}">Следующая</a>
                </li>
            </div>
        </ul>
    </nav>

{% endblock %}

{% block footer %}
<footer class="py-4 bg-dark">
    <div class="container">
        <p class="m-0 text-center text-white">Copyright &copy; Home Python Hub Studio 2023</p>
    </div>
</footer>
{% endblock %}







                    

goods/templates/goods/product.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<div class="container mt-5">
    <div class="card mb-4 custom-shadow">
        <div class="row">
            <!-- Миниатюры -->
            <div class="col-md-4">
                <img src="{{ product.image.url }}"
                     class="img-thumbnail" data-bs-toggle="modal" data-bs-target="#imageModal1">
            </div>

            <div class="col-md-4">
                <p class="product_id mt-3">ID: {{ product.id }}</p>  <!-- Здесь выводится ID продукта -->
            </div>
        </div>

        <!-- Увеличить изображение в модальном окне -->
        <div class="modal fade" id="imageModal1" tabindex="-1" aria-labelledby="imageModal1Label" aria-hidden="true">
            <div class="modal-dialog modal-lg">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="imageModal1Label">{{ product.name }}</h5>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Закрыть"></button>
                    </div>
                    <div class="modal-body">
                        <img src="{{ product.image.url }}" class="img-fluid" alt="Изображение 1">
                    </div>
                </div>
            </div>
        </div>

        <!-- Описание товара -->
        <div class="card-body">
            <p class="card-text">Цена: <strong>{{ product.sell_price }} $</strong></p>
            <h5 class="card-title">{{ product.name }}</h5>
            <p class="card-text">{{ product.description }}</p>
            <form action="{% url 'myapp:cart_add' product.id %}" method="POST">
                {% csrf_token %}
                <input type="number" name="quantity" min="1" value="1" style="width: 60px; margin-right: 10px;">
                <button type="submit" class="btn btn-dark">Добавить в корзину</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}