kku/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('profile/', include('users.urls', namespace='users_profile')),
    path('', include('myapp.urls', namespace='myapp')),
    path('catalog/', include('goods.urls', namespace='catalog')),
    path('users/', include('users.urls', namespace='users')),
]


if settings.DEBUG:
    urlpatterns += [
        path('debug/', include('debug_toolbar.urls')),
    ]
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from users import views

app_name = 'users'

urlpatterns = [
    path('login/', views.login, name='login'),
    path('registration/', views.registration, name='registration'),
    path('profile/', views.profile, name='profile'),
    path('logout/', views.logout, name='logout'),
]

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

class User(AbstractUser):
    image = models.ImageField(upload_to='users_images', blank=True, null=True)


    class Meta:
        db_table = 'user'
        verbose_name = "Пользователя"
        verbose_name_plural = "Пользователи"

    def __str__(self) -> str:
        return self.username

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm, UserChangeForm
from .models import User

class UserRegistrationForm(UserCreationForm):
    first_name = forms.CharField(
        widget=forms.TextInput(attrs={
            "class": "form-control",
            "placeholder": "Введите ваше имя"
        })
    )
    last_name = forms.CharField(
        widget=forms.TextInput(attrs={
            "class": "form-control",
            "placeholder": "Введите вашу фамилию"
        })
    )
    username = forms.CharField(
        widget=forms.TextInput(attrs={
            "class": "form-control",
            "placeholder": "Введите имя пользователя"
        })
    )
    email = forms.EmailField(
        widget=forms.EmailInput(attrs={
            "class": "form-control",
            "placeholder": "Введите ваш email"
        })
    )
    password1 = forms.CharField(
        widget=forms.PasswordInput(attrs={
            "class": "form-control",
            "placeholder": "Введите пароль"
        })
    )
    password2 = forms.CharField(
        widget=forms.PasswordInput(attrs={
            "class": "form-control",
            "placeholder": "Повторите пароль"
        })
    )

    class Meta:
        model = User
        fields = (
            "first_name",
            "last_name",
            "username",
            "email",
            "password1",
            "password2",
        )

class UserLoginForm(AuthenticationForm):
    username = forms.CharField(
        widget=forms.TextInput(attrs={
            "class": "form-control",
            "placeholder": "Введите имя пользователя"
        })
    )
    password = forms.CharField(
        widget=forms.PasswordInput(attrs={
            "class": "form-control",
            "placeholder": "Введите пароль"
        })
    )

    class Meta:
        model = User
        fields = ("username", "password")

class ProfileForm(UserChangeForm):
    first_name = forms.CharField(
        widget=forms.TextInput(attrs={
            "class": "form-control",
            "placeholder": "Введите ваше имя"
        })
    )
    last_name = forms.CharField(
        widget=forms.TextInput(attrs={
            "class": "form-control",
            "placeholder": "Введите вашу фамилию"
        })
    )
    username = forms.CharField(
        widget=forms.TextInput(attrs={
            "class": "form-control",
            "placeholder": "Введите имя пользователя"
        })
    )
    email = forms.EmailField(
        widget=forms.EmailInput(attrs={
            "class": "form-control",
            "placeholder": "Введите ваш email"
        })
    )
    image = forms.ImageField(
        widget=forms.FileInput(attrs={"class": "form-control mt-3"}),
        required=False
    )

    class Meta:
        model = User
        fields = (
            "first_name",
            "last_name",
            "username",
            "email",
            "image",
        )

users/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.contrib import auth
from django.urls import reverse
from users.forms import UserRegistrationForm, UserLoginForm

def login(request):
    if request.method == 'POST':
        form = UserLoginForm(data=request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = auth.authenticate(request, username=username, password=password)
            if user:
                auth.login(request, user)
                return redirect(reverse('myapp:index'))
    else:
        form = UserLoginForm()

    context = {
        'title': 'Home Авторизация',
        'form': form
    }
    return render(request, 'users/login.html', context)

def registration(request):
    if request.method == 'POST':
        form = UserRegistrationForm(data=request.POST)
        if form.is_valid():
            form.save()
            user = form.instance
            auth.login(request, user)
            return redirect(reverse('user:login'))
    else:
        form = UserRegistrationForm()

    context = {
        'title': 'Home Регистрация',
        'form': form
    }
    return render(request, 'users/registration.html', context)

def profile(request) -> HttpResponse:
    context = {
        'title': 'Home Кабинет'
    }
    return render(request, 'users/profile.html', context)

def logout(request) -> HttpResponse:
    auth.logout(request)
    return redirect(reverse('main:index'))

users/templates/users/login.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<div class="row">
    <div class="container mt-5">
        <div class="row justify-content-center">
            <div class="col-md-6 bg-white p-4 mb-4 mx-3 rounded custom-shadow">
                <h2 class="text-center mb-4">Авторизация</h2>
                <form action="{% url 'users:login' %}" method="post">
                    {% csrf_token %}

                    <div class="mb-3">
                        <label for="{{ form.username.id_for_label }}" class="form-label">Имя пользователя</label>
                        <input type="text" name="username" id="{{ form.username.id_for_label }}" class="form-control"
                               value="{% if form.username.value %}{{ form.username.value }}{% endif %}">
                        {% if form.username.errors %}
                            <div class="text-danger">{{ form.username.errors|join:', ' }}</div>
                        {% endif %}
                    </div>
                    <div class="mb-3">
                        <label for="{{ form.password.id_for_label }}" class="form-label">{{ form.password.label }}</label>
                        <input type="password" name="password" id="{{ form.password.id_for_label }}" class="form-control"
                               value="{% if form.password.value %}{{ form.password.value }}{% endif %}">
                        {% if form.password.errors %}
                            <div class="text-danger">{{ form.password.errors|join:', ' }}</div>
                        {% endif %}
                    </div>
                    {% if form.non_field_errors %}
                        <div class="alert alert-danger">Введите правильное имя пользователя или пароль.</div>
                    {% endif %}
                    <button type="submit" class="btn btn-dark btn-block">Войти</button>
                </form>
                <div class="mt-3">
                    <a href="#">Забыли пароль?</a> | <a href="{% url 'users:registration' %}">Создать аккаунт</a>
                </div>
                <hr>
                <div class="text-center">
                    <p>Или авторизуйтесь через:</p>
                    <a href="#" class="btn btn-dark">
                        <img class="mx-1" src="{% static 'deps/icons/google.svg' %}" alt="Google Icon" width="16" height="16">
                        Google
                    </a>
                    <a href="#" class="btn btn-dark">
                        <img class="mx-1" src="{% static 'deps/icons/facebook.svg' %}" alt="Facebook Icon" width="16" height="16">
                        Facebook
                    </a>
                    <a href="#" class="btn btn-dark">
                        <img class="mx-1" src="{% static 'deps/icons/github.svg' %}" alt="GitHub Icon" width="16" height="16">
                        GitHub
                    </a>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

users/templates/users/profile.html
{% extends "base.html" %}
{% load static %}

{% block content%}
<div class="row">
  <div class="container mt-5">
    <div class="row">
      <!-- Профиль с данными пользователя -->
      <div class="col-md-5">
        <div class=" bg-white p-4 mb-4 mx-2 rounded custom-shadow">
          <h3 class="text-center mb-4">Профиль пользователя</h3>
          <form>
            <div class="row">
              <div class="col-md-12 mb-3 text-center">
                <img src="{% static 'deps/images/baseavatar.jpg' %}"
                     alt="Аватар пользователя" class="img-fluid rounded-circle"
                     style="max-width: 150px;">
                <input type="file" class="form-control mt-3" id="avatar"
                       accept="image/*">
              </div>
              <div class="col-md-12 mb-3">
                <label for="firstName" class="form-label">Имя*</label>
                <input type="text" class="form-control" id="firstName"
                       placeholder="Введите ваше имя" value="" required>
              </div>
              <div class="col-md-12 mb-3">
                <label for="lastName" class="form-label">Фамилия*</label>
                <input type="text" class="form-control" id="lastName"
                       placeholder="Введите вашу фамилию" value="" required>
              </div>
              <div class="col-md-12 mb-3">
                <label for="username" class="form-label">Имя пользователя*</label>
                <input type="text" class="form-control" id="username"
                       placeholder="Введите ваше имя пользователя" value="" required>
              </div>
              <div class="col-md-12 mb-3">
                <label for="email" class="form-label">Email*</label>
                <input type="email" class="form-control" id="email"
                       placeholder="Введите ваш email *youremail@example.com" value=""
                       required>
              </div>
            </div>
            <button type="submit" class="btn btn-dark">Сохранить</button>
          </form>
        </div>
      </div>
      <!-- Корзина -->
      <div class="col-md-7">
        <div class=" bg-white p-4 mb-4 mx-2 rounded custom-shadow">
          <h3 class="text-center mb-4">Корзина</h3>
          <div class="container" id="cart-items-container">
            <!-- Разметка корзины -->
            <!-- Закончилась разметка корзины -->
          </div>
          <a class="btn btn-dark" href="../orders/create_order.html">
            Оформить заказ
          </a>
        </div>
      </div>
      <!-- Оформленные заказы -->
      <div class="col-md-12">
        <div class=" bg-white p-4 mb-4 mx-2 rounded custom-shadow">
          <h3 class="text-center mb-4">Мои заказы</h3>
          <!-- Разметка заказов -->
          <div class="container">
            <div class="accordion" id="accordionExample">
              <div class="accordion-item">
                <h2 class="accordion-header" id="heading1">
                  <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapse1" aria-expanded="false" aria-controls="collapse1">
                    Заказ № 256 - 09 сентября 2023 9:04 | Статус:<strong class="mx-2"> В обработке</strong>
                  </button>
                </h2>
                <div id="collapse1" class="accordion-collapse collapse show" aria-labelledby="heading1" data-bs-parent="#accordionExample">
                  <div class="accordion-body">
                    <table class="table table-dark table-hover">
                      <thead>
                      <tr>
                        <th>Товар</th>
                        <th>Количество</th>
                        <th>Цена</th>
                        <th>Общая стоимость</th>
                      </tr>
                      </thead>
                      <tbody>
                      <tr>
                        <td><a class="text-white" href="#">Комплект стол и три стула</a></td>
                        <td>1</td>
                        <td>255.00 $</td>
                        <td>255.00 $</td>
                      </tr>
                      </tbody>
                    </table>
                    <div class="d-flex justify-content-between">
                      <p><strong>Итого:</strong></p>
                      <p><strong>255.00 $</strong></p>
                    </div>
                  </div>
                </div>
              </div>
              <div class="accordion-item">
                <h2 class="accordion-header" id="heading2">
                  <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapse2" aria-expanded="false" aria-controls="collapse2">
                    Заказ № 248 - 01 августа 2023 11:28 | Статус: <strong>Получен</strong>
                  </button>
                </h2>
                <div id="collapse2" class="accordion-collapse collapse" aria-labelledby="heading2" data-bs-parent="#accordionExample">
                  <div class="accordion-body">
                    <table class="table table-dark table-hover">
                      <thead>
                      <tr>
                        <th>Товар</th>
                        <th>Количество</th>
                        <th>Цена</th>
                        <th>Общая стоимость</th>
                      </tr>
                      </thead>
                      <tbody>
                      <tr>
                        <td><a class="text-white" href="#">Стул офисный</a></td>
                        <td>2</td>
                        <td>30.00 $</td>
                        <td>60.00 $</td>

                      </tr>
                      </tbody>
                    </table>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <!-- Закончилась разметка заказов -->
        </div>
      </div>
    </div>
  </div>
</div>
</div>
{% endblock %}

users/templates/users/registration.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<div class="row">
    <div class="container mt-5">
        <div class="row justify-content-center">
            <div class="col-md-9 bg-white p-4 mb-5 mx-2 rounded custom-shadow">
                <h2 class="text-center mb-4">Регистрация</h2>
                <form action="{% url 'users:registration' %}" method="post">
                    {% csrf_token %}
                    <div class="row">
                        <div class="col-md-6 mb-3">
                            <label for="id_first_name" class="form-label">Имя*</label>
                            <input type="text" class="form-control" id="id_first_name" name="first_name" placeholder="Введите ваше имя" required>
                        </div>
                        <div class="col-md-6 mb-3">
                            <label for="id_last_name" class="form-label">Фамилия*</label>
                            <input type="text" class="form-control" id="id_last_name" name="last_name" placeholder="Введите вашу фамилию" required>
                        </div>
                        <div class="col-md-6 mb-3">
                            <label for="id_username" class="form-label">Имя пользователя*</label>
                            <input type="text" class="form-control" id="id_username" name="username" placeholder="Введите ваше имя пользователя" required>
                        </div>
                        <div class="col-md-6 mb-3">
                            <label for="id_email" class="form-label">Email*</label>
                            <input type="email" class="form-control" id="id_email" name="email" placeholder="Введите ваш email" required>
                        </div>
                        <div class="col-md-6 mb-3">
                            <label for="id_password1" class="form-label">Пароль*</label>
                            <input type="password" class="form-control" id="id_password1" name="password1" placeholder="Введите пароль" required>
                        </div>
                        <div class="col-md-6 mb-3">
                            <label for="id_password2" class="form-label">Подтверждение пароля*</label>
                            <input type="password" class="form-control" id="id_password2" name="password2" placeholder="Подтвердите пароль" required>
                        </div>
                    </div>
                    <button type="submit" class="btn btn-dark btn-block">Зарегистрироваться</button>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}