kku/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('profile/', include('users.urls', namespace='users_profile')),
    path('', include('myapp.urls', namespace='myapp')),
    path('catalog/', include('goods.urls', namespace='catalog')),
    path('users/', include('users.urls', namespace='users')),
]


if settings.DEBUG:
    urlpatterns += [
        path('debug/', include('debug_toolbar.urls')),
    ]
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myapp/urls.py
from django.urls import path
from myapp import views  # Импортируем представления из приложения myapp

app_name = 'myapp'  # Устанавливаем пространство имен для маршрутов

urlpatterns = [
    path('', views.index, name='index'),  # Главная страница
    path('about/', views.about, name='about'),  # Страница 'О нас'
    path('cart/', views.cart_detail, name='cart_detail'),  # Страница корзины
    path('cart/add/<int:product_id>/', views.cart_add, name='cart_add'),  # Добавить товар в корзину
    path('cart/remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
]

myapp/models.py
from django.db import models

# Create your models here.

myapp/views.py
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404, redirect
from goods.models import Categories, Products
from .cart import Cart

def index(request):
    categories = Categories.objects.all()  # Получаем все категории

    context = {
        'title': 'Home - Главная',
        'content': "Магазин мебели HOME",
        'categories': categories,  # Добавляем категории в контекст
    }

    return render(request, 'myapp/index.html', context)

def about(request):
    context = {
        'title': 'Home - О нас',
        'content': "О нас",
        'text_on_page': (
            "Мы - команда профессионалов, специализирующихся на продаже мебели, "
            "предлагающая широкий ассортимент товаров для вашего дома и офиса. "
            "Наши специалисты с радостью помогут вам выбрать идеальные решения, "
            "которые сочетат стиль, комфорт и функциональность. "
            "Мы стремимся к качеству и заботимся о каждом клиенте, "
            "предоставляя только лучшие материалы и современные технологии. "
            "С нами вы найдете мебель, которая не только украсит ваше пространство, "
            "но и станет отражением вашего уникального стиля."
        )
    }

    return render(request, 'myapp/about.html', context)


def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Products, id=product_id)

    quantity = int(request.POST.get('quantity', 1))  # Получаем количество из формы
    cart.add(product, quantity)  # Добавляем продукт в корзину с указанным количеством
    return redirect('myapp:cart_detail')  # Перенаправляем на страницу корзины


def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Products, id=product_id)
    cart.remove(product)  # Удаляем продукт из корзины
    return redirect('myapp:cart_detail')  # Перенаправляем на страницу корзины

def cart_detail(request):
    cart = Cart(request)
    context = {
        'cart': cart,  # Передаем корзину в контекст
    }
    return render(request, 'myapp/cart/detail.html', context)  # Убедитесь, что путь к шаблону правильный

myapp/templates/myapp/about.html
{% extends "main/base.html" %}
{% load static %}

{% block css %}
    <link rel="stylesheet" href="{% static 'deps/css/my_footer_css.css' %}">
{% endblock %}

{% block content %}
<main class="mt-5 pt-5 bg-white custom-shadow rounded">
    <h2 class="m-2"><strong>{{ content }}</strong></h2>
    <p class="m-2">{{ text_on_page }}</p>
</main>
{% endblock %}

{% block footer %}
<footer class="py-4 bg-dark">
    <div class="container">
        <p class="m-0 text-center text-white">Copyright &copy; Home {{ current_year }}</p>
    </div>
</footer>
{% endblock %}

myapp/templates/myapp/detail.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<div class="container mt-5">
    <h1>Корзина</h1>
    {% if cart %}
        <table class="table">
            <thead>
                <tr>
                    <th>Товар</th>
                    <th>Количество</th>
                    <th>Цена</th>
                    <th>Итого</th>
                    <th>Действия</th>
                </tr>
            </thead>
            <tbody>
                {% for item in cart %}
                <tr>
                    <td>{{ item.product.name }}</td>
                    <td>{{ item.quantity }}</td>
                    <td>{{ item.product.sell_price }} $</td>
                    <td>{{ item.product.sell_price|multiply:item.quantity }} $</td>
                    <td>
                        <form action="{% url 'myapp:cart_remove' item.product.id %}" method="POST">
                            {% csrf_token %}
                            <button type="submit" class="btn btn-danger">Удалить</button>
                        </form>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
        <h3>Итого: {{ total }} $</h3>
    {% else %}
        <p>Ваша корзина пуста.</p>
    {% endif %}
</div>
{% endblock %}

myapp/templates/myapp/index.html
{% extends "base.html" %}
{% load static %}

    {% block css %}
        <link rel="stylesheet" href="{% static 'deps/css/my_footer_css.css' %}">
    {% endblock %}


    {% block content %}
        <h1 class="mt-5 pt-5"><strong>{{ content }}</strong></h1>
    {% endblock %}

    {% block footer %}
        <footer class="py-4 bg-dark">
            <div class="container">
                <p class="m-0 text-center text-white">Copyright &copy; Home 2023</p>
            </div>
        </footer>
    {% endblock %}